# Look into one community with fully coexisting alternative stable state

In [1]:
import torch
from pathlib import Path
from scipy.io import savemat
import sys
sys.path.append('../src/')
from solving import FindAltSS
from optimizing import trainI, NormalG
datapath = Path('../data/')

In [2]:
vars = torch.load(datapath/'min_dim12.pt')
G = vars["G"]
C = vars["C"]
Rs = vars["Rs"]
Ss = vars["Ss"]
div = vars["div"]
"""
forjl = {"C":C.numpy(), "G": G.numpy(),"Rs": Rs.numpy(), 
             "Ss": Ss.numpy()}
savemat("../data/forjl.mat", forjl)
"""
_, solutions, spe_name = FindAltSS(G,C,Ss,Rs)

In [3]:
Ss

tensor([0.7043, 0.9914, 0.1405, 0.7109])

In [4]:
Rs

tensor([0.5490, 0.6257, 0.8113, 0.1844])

In [5]:
EGC, Estd, CD = trainI(G,C,n=0.5)

In [6]:
CDsimp = NormalG(CD)
Gsimp = NormalG(G)

In [7]:
Gsimp

tensor([[0.1915, 0.4172, 0.2255, 0.1658],
        [0.0539, 0.5042, 0.3614, 0.0805],
        [0.5222, 0.1287, 0.2867, 0.0625],
        [0.3456, 0.1947, 0.2362, 0.2235]])

In [8]:
CDsimp

tensor([[0.2151, 0.4427, 0.2759, 0.0662],
        [0.2239, 0.4088, 0.2756, 0.0916],
        [0.3004, 0.2482, 0.3299, 0.1216],
        [0.4290, 0.2240, 0.2431, 0.1039]])

In [9]:
solutions[0][0]

tensor([0.7043, 0.9914, 0.1405, 0.7109, 0.5490, 0.6257, 0.8113, 0.1844])

In [11]:
solutions[1][0]

tensor([1.1118, 3.0352, 0.5984, 0.6657, 0.7067, 0.1690])

In [12]:
spe_name

[tensor([0, 1, 2, 3]), tensor([0, 2])]